title: Tom R. Leppard, PhD
logo: /asset/Profile_pic.jpg
description: I am a father, a Londoner, a former rugby player, and a postdoctoral scholar for the Data Science and AI Academy at North Carolina State University. 
theme: jekyll-theme-minimal

